@startuml classes

hide empty members


class IntersectionScene {
    void start(int msec = 0)
    void stop()
    void step()
    void onStep()

    QBasicTimer timer_;
    std::map<int, PathNode> pathNodes_;
}

QGraphicsScene <|-- IntersectionScene

IntersectionScene o-- BaseItem

class BaseItem {
    void step();
    {abstract} void onStep();

    int id;
}

class CarItem {
    qreal velocity_;
    qreal distance_;

    --signals--
    void endReached();
}

BaseItem <|-- CarItem

class PathItem {
    void onStep();

    std::vector<CarItem*> cars_;
    PathNode* beginNode_;
    PathNode* endNode_;
}

BaseItem <|-- PathItem

class PathNode {
    int id_;
    std::map<int, PathItem*> prevPaths_;
    std::map<int, PathItem*> nextPaths_;
}

IntersectionScene o-- PathNode

class CarAgent {
    CarItem* car_;
}

CarAgent -- CarItem

@enduml